[theme]
primaryColor = "#e50914"
backgroundColor = "#141414"
secondaryBackgroundColor = "#2a2a2a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
